---
# Configure openshift-cam

- name: service is enabled and started
  service:
    name: "{{ item }}"
    enabled: true
    state: started
  become: true
  loop: "{{ openshift-cam_services_enable }}"
  when: openshift-cam_enable_service
