---
# Template configuration files for openshift-cam

- name: template is copied
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  become: true
  loop: "{{ openshift-cam_templates_copy }}"
  when: openshift-cam_copy_templates
